setwd("C:/Users/Tao25/Documents/Liposarcoma/2")
cat("Stage 1: Data Preparation\n")
source("scripts/stage1_preparation/01_download_preprocess.R")
source("scripts/stage1_preparation/02_cohort_overview.R")
cat("Stage 2: Prognostic Model\n")
source("scripts/stage2_prognostic_model/03_survival_analysis.R")
source("scripts/stage2_prognostic_model/04_model_performance.R")
cat("Stage 3: Biological Mechanism\n")
source("scripts/stage3_mechanism/05_pathway_analysis.R")
source("scripts/stage3_mechanism/06_immune_landscape.R")
cat("Stage 4: Clinical Translation\n")
source("scripts/stage4_clinical_translation/07_nomogram.R")
source("scripts/stage2_prognostic_model/05_GSE30929_validation.R")
cat("Pipeline completed.\n")
